export const blogPosts = [
  {
    id: 1,
    titleKey: "blog.post1.title",
    excerptKey: "blog.post1.excerpt",
    image: "/placeholder.svg?height=300&width=400",
    author: "Ahmed Hassan",
    date: "2024-01-15",
    categoryKey: "blog.category.nutrition",
    readTime: 5,
  },
  {
    id: 2,
    titleKey: "blog.post2.title",
    excerptKey: "blog.post2.excerpt",
    image: "/placeholder.svg?height=300&width=400",
    author: "Fatima Benali",
    date: "2024-01-10",
    categoryKey: "blog.category.farming",
    readTime: 7,
  },
  {
    id: 3,
    titleKey: "blog.post3.title",
    excerptKey: "blog.post3.excerpt",
    image: "/placeholder.svg?height=300&width=400",
    author: "Omar Alami",
    date: "2024-01-05",
    categoryKey: "blog.category.sustainability",
    readTime: 6,
  },
  {
    id: 4,
    titleKey: "blog.post4.title",
    excerptKey: "blog.post4.excerpt",
    image: "/placeholder.svg?height=300&width=400",
    author: "Aicha Benali",
    date: "2024-01-01",
    categoryKey: "blog.category.recipes",
    readTime: 3,
  },
  {
    id: 5,
    titleKey: "blog.post5.title",
    excerptKey: "blog.post5.excerpt",
    image: "/placeholder.svg?height=300&width=400",
    author: "Omar Alami",
    date: "2023-12-28",
    categoryKey: "blog.category.business",
    readTime: 8,
  },
  {
    id: 6,
    titleKey: "blog.post6.title",
    excerptKey: "blog.post6.excerpt",
    image: "/placeholder.svg?height=300&width=400",
    author: "Ahmed Hassan",
    date: "2023-12-20",
    categoryKey: "blog.category.seasonal",
    readTime: 4,
  },
  {
    id: 7,
    titleKey: "news.morocco.export.spain.q1_2025",
    excerptKey: "news.morocco.export.spain.q1_2025.excerpt",
    image: "/placeholder.svg?height=300&width=400",
    author: "Hespress",
    date: "2025-06-07",
    categoryKey: "news.category.trade",
    readTime: 2,
  },
  {
    id: 8,
    titleKey: "news.morocco.global_export_growth.strategy",
    excerptKey: "news.morocco.global_export_growth.strategy.excerpt",
    image: "/placeholder.svg?height=300&width=400",
    author: "Morocco World News",
    date: "2025-04-01",
    categoryKey: "news.category.agriculture",
    readTime: 3,
  },
  {
    id: 9,
    titleKey: "news.morocco.exports.rebound.2024_25",
    excerptKey: "news.morocco.exports.rebound.2024_25.excerpt",
    image: "/placeholder.svg?height=300&width=400",
    author: "Hespress",
    date: "2025-06-02",
    categoryKey: "news.category.economy",
    readTime: 3,
  },
  {
    id: 10,
    titleKey: "news.morocco.zucchini.switzerland",
    excerptKey: "news.morocco.zucchini.switzerland.excerpt",
    image: "/placeholder.svg?height=300&width=400",
    author: "Hespress",
    date: "2025-06-27",
    categoryKey: "news.category.trade",
    readTime: 2,
  },
]
