export const blogPosts = [
  {
    id: 1,
    title: "Rainfall Impact on the 2024 Harvest",
    excerpt:
      "How shifting rainfall patterns are affecting vegetable production across Morocco's farms.",
    titleKey: "blog.rainfall_impact_2024.title",
    excerptKey: "blog.rainfall_impact_2024.excerpt",
    image: "/grainHarvest.png",
    author: "Reda El Amrani",
    date: "2024-05-12",
    category: "Farming",
    categoryKey: "blog.category.farming",
    readTime: 6,
  },
  {
    id: 2,
    title: "Turning Sand into a Green Oasis",
    excerpt:
      "Discover sustainable irrigation methods that transform arid land into productive farmland.",
    titleKey: "blog.sand_to_green_oasis.title",
    excerptKey: "blog.sand_to_green_oasis.excerpt",
    image: "/desertToForest.png",
    author: "Salma Chafai",
    date: "2024-08-09",
    category: "Sustainability",
    categoryKey: "blog.category.sustainability",
    readTime: 7,
  },
  {
    id: 3,
    title: "No-Till Farming Expansion in Morocco",
    excerpt:
      "A look at how no-till agriculture is boosting soil health and crop resilience.",
    titleKey: "blog.no_till_expansion.title",
    excerptKey: "blog.no_till_expansion.excerpt",
    image: "/climateResilience.png",
    author: "Youssef Belkadi",
    date: "2024-11-03",
    category: "Agriculture",
    categoryKey: "news.category.agriculture",
    readTime: 5,
  },
  {
    id: 4,
    title: "Green Deal Opportunity for Moroccan Exporters",
    excerpt:
      "How international sustainability policies are opening new markets for fresh produce.",
    titleKey: "blog.green_deal_opportunity.title",
    excerptKey: "blog.green_deal_opportunity.excerpt",
    image: "/modernTools.png",
    author: "Nadia El Fassi",
    date: "2025-01-15",
    category: "Economy",
    categoryKey: "news.category.economy",
    readTime: 6,
  },
  {
    id: 5,
    title: "Food Quality Standards for Export",
    excerpt:
      "Why rigorous certifications matter for Moroccan produce shipped overseas.",
    titleKey: "blog.food_quality_standards.title",
    excerptKey: "blog.food_quality_standards.excerpt",
    image: "/safety.png",
    author: "Mohamed Lahlou",
    date: "2025-02-10",
    category: "Business",
    categoryKey: "blog.category.business",
    readTime: 5,
  },
  {
    id: 6,
    title: "Oasis Irrigation Innovation",
    excerpt:
      "New water-saving systems support sustainable fruit and vegetable production.",
    titleKey: "blog.oasis_irrigation_innovation.title",
    excerptKey: "blog.oasis_irrigation_innovation.excerpt",
    image: "/oisis.png",
    author: "Khadija Bennani",
    date: "2025-03-05",
    category: "Sustainability",
    categoryKey: "blog.category.sustainability",
    readTime: 4,
  },
  {
    id: 7,
    title: "Morocco Exports to Spain in Q1 2025",
    excerpt:
      "A market update on Moroccan fresh produce shipments to Spain this quarter.",
    titleKey: "news.morocco.export.spain.q1_2025",
    excerptKey: "news.morocco.export.spain.q1_2025.excerpt",
    image: "/exportSpain.png",
    author: "Hespress",
    date: "2025-06-07",
    category: "Trade",
    categoryKey: "news.category.trade",
    readTime: 2,
  },
  {
    id: 8,
    title: "Global Export Growth Strategy",
    excerpt:
      "How Morocco is strengthening its agricultural exports through innovation and partnerships.",
    titleKey: "news.morocco.global_export_growth.strategy",
    excerptKey: "news.morocco.global_export_growth.strategy.excerpt",
    image: "/moroccoTech.png",
    author: "Morocco World News",
    date: "2025-04-01",
    category: "Agriculture",
    categoryKey: "news.category.agriculture",
    readTime: 3,
  },
  {
    id: 9,
    title: "Exports Rebound in 2024/25",
    excerpt:
      "An overview of the recovering Moroccan export market for fresh produce.",
    titleKey: "news.morocco.exports.rebound.2024_25",
    excerptKey: "news.morocco.exports.rebound.2024_25.excerpt",
    image: "/moroccoDev.png",
    author: "Hespress",
    date: "2025-06-02",
    category: "Economy",
    categoryKey: "news.category.economy",
    readTime: 3,
  },
  {
    id: 10,
    title: "Moroccan Zucchini Finds Swiss Market",
    excerpt:
      "Swiss buyers are placing new orders for Moroccan zucchini as quality demand rises.",
    titleKey: "news.morocco.zucchini.switzerland",
    excerptKey: "news.morocco.zucchini.switzerland.excerpt",
    image: "/zucchini.png",
    author: "Hespress",
    date: "2025-06-27",
    category: "Trade",
    categoryKey: "news.category.trade",
    readTime: 2,
  },
];
