export const blogPosts = [
  {
    id: 1,
    titleKey: "blog.rainfall_impact_2024.title",
    excerptKey: "blog.rainfall_impact_2024.excerpt",
    image: "/grainHarvest.png",
    author: "Reda El Amrani",
    date: "2024-05-12",
    categoryKey: "blog.category.farming",
    readTime: 6,
  },
  {
    id: 2,
    titleKey: "blog.sand_to_green_oasis.title",
    excerptKey: "blog.sand_to_green_oasis.excerpt",
    image: "/desertToForest.png",
    author: "Salma Chafai",
    date: "2024-08-09",
    categoryKey: "blog.category.sustainability",
    readTime: 7,
  },
  {
    id: 3,
    titleKey: "blog.no_till_expansion.title",
    excerptKey: "blog.no_till_expansion.excerpt",
    image: "/climateResilience.png",
    author: "Youssef Belkadi",
    date: "2024-11-03",
    categoryKey: "news.category.agriculture",
    readTime: 5,
  },
  {
    id: 4,
    titleKey: "blog.green_deal_opportunity.title",
    excerptKey: "blog.green_deal_opportunity.excerpt",
    image: "/modernTools.png",
    author: "Nadia El Fassi",
    date: "2025-01-15",
    categoryKey: "news.category.economy",
    readTime: 6,
  },
  {
    id: 5,
    titleKey: "blog.food_quality_standards.title",
    excerptKey: "blog.food_quality_standards.excerpt",
    image: "/safety.png",
    author: "Mohamed Lahlou",
    date: "2025-02-10",
    categoryKey: "blog.category.business",
    readTime: 5,
  },
  {
    id: 6,
    titleKey: "blog.oasis_irrigation_innovation.title",
    excerptKey: "blog.oasis_irrigation_innovation.excerpt",
    image: "/oisis.png",
    author: "Khadija Bennani",
    date: "2025-03-05",
    categoryKey: "blog.category.sustainability",
    readTime: 4,
  },
  {
    id: 7,
    titleKey: "news.morocco.export.spain.q1_2025",
    excerptKey: "news.morocco.export.spain.q1_2025.excerpt",
    image: "/exportSpain.png",
    author: "Hespress",
    date: "2025-06-07",
    categoryKey: "news.category.trade",
    readTime: 2,
  },
  {
    id: 8,
    titleKey: "news.morocco.global_export_growth.strategy",
    excerptKey: "news.morocco.global_export_growth.strategy.excerpt",
    image: "/moroccoTech.png",
    author: "Morocco World News",
    date: "2025-04-01",
    categoryKey: "news.category.agriculture",
    readTime: 3,
  },
  {
    id: 9,
    titleKey: "news.morocco.exports.rebound.2024_25",
    excerptKey: "news.morocco.exports.rebound.2024_25.excerpt",
    image: "/moroccoDev.png",
    author: "Hespress",
    date: "2025-06-02",
    categoryKey: "news.category.economy",
    readTime: 3,
  },
  {
    id: 10,
    titleKey: "news.morocco.zucchini.switzerland",
    excerptKey: "news.morocco.zucchini.switzerland.excerpt",
    image: "/zucchini.png",
    author: "Hespress",
    date: "2025-06-27",
    categoryKey: "news.category.trade",
    readTime: 2,
  },
]
